services:
  - type: worker
    name: kaskad-vk-bot
    runtime: node
    buildCommand: npm install
    startCommand: node scripts/long-polling.cjs
    envVars:
      - key: RENDER_EXTERNAL_URL
        sync: false
      - key: VK_GROUP1_TOKEN
        sync: false
      - key: VK_GROUP2_TOKEN
        sync: false
      - key: VK_GROUP1_ID
        sync: false
      - key: VK_GROUP2_ID
        sync: false
      - key: VK_CHAT_RUKOVODSTVO_ID
        sync: false
      - key: VK_CHAT_SS_ID
        sync: false
      - key: VK_CHAT_UCHEBNY_ID
        sync: false
      - key: VK_CHAT_DOSKA_ID
        sync: false
      - key: VK_CHAT_DISPETCHERSKAYA_ID
        sync: false
      - key: VK_CHAT_FLUDILKA_ID
        sync: false
      - key: VK_CHAT_ZHURNAL_ID
        sync: false
      - key: VK_CHAT_SPONSOR_ID
        sync: false
